### ISSUE TITLE
Doesn't work with Compact message view

### ISSUE THREAD

**Issue by evilcommand** [EnKrypt/DiscordEncryption#1]
hey i installed it my friend can see dycriped message fine but i cant 
we installed ad same time adn i even tryed on my laptop fresh install discord adn better discord but doesnt seem to dycript doesnt give any errors eather any ideas ?

**Comment by EnKrypt** [comment]
Can you confirm that both of you are using the same secret?

Can I have a screenshot of what you're seeing in place of the decrypted messages?

**Comment by EnKrypt** [comment]
So for anyone reading this in the future, I've corresponded with @evilcommand over email to get more info, and this is what the issue looked like :

![preview](https://i.imgur.com/kmXtaGW.png)

Note that the OP had the plugin setup and enabled correctly, and he had the key required to decrypt it, but the plugin failed to do so.

The both of us then tested this on a separate Discord server to reproduce the issue and we figured out 
that this was happening because the OP had selected **Compact** view in Settings under Appearances.

Since I'd developed and tested the plugin (on multiple OS with multiple users on different Discord servers) with the **Cozy** view instead, it did not even occur to me that the other view exists, and will break the plugin.  
:clap: *Well done me*

I will update the title of this post and submit a patch soon such that it works with the **Compact** view as well. If you stumble across this issue before that happens, please switch to the **Cozy** view for the time being.

**Comment by EnKrypt** [comment]
This is now fixed. The current version of the plugin should also support **Compact** view.

**Comment by evilcommand** [comment]
cool wil download

**Comment by DasCanard** [comment]
still not working

**Comment by EnKrypt** [comment]
@DasCanard Are you using the latest version of the plugin?

The primary issue with Compact view was solved as stated above. Sometimes you might have to switch between channels or servers once for it to show up and render properly.

If that is still not helping, reply with a screenshot and I'll have a look.
